### ISSUE TITLE
"SyntaxError: Unexpected token ILLEGAL" and "SyntaxError: Unexpected reserved word"

### ISSUE THREAD

**Issue by matteyeux** [dzt/twitter2slack#1]
Hey Peter, I wanted to test this project which seems very cool and I would like to implement it on Slack, but I got some issues : 

### SyntaxError: Unexpected token ILLEGAL

Here is the output 
```
$ nodejs index

/home/pi/Documents/twitter2slack/index.js:37
                console.log(`Tweet with image recieved (${data.id})`);
                            ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```
It seems you use " ` " instead of " ' "  when you call console.log

### SyntaxError: Unexpected reserved word
I fixed it myself then run into another issue I don't understand : 
```
/home/pi/Documents/twitter2slack/node_modules/slackbots/index.js:10
class Bot extends EventEmitter {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Documents/twitter2slack/index.js:10:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Is it related to the first case ?
I'm running it on RPi Raspbian 
Btw I never touched JS before, I may be 100% wrong

**Comment by dzt** [comment]
That's intentional, I know what I'm doing. You're not on the LTS version of Nodejs.

Thanks,
Peter

**Comment by matteyeux** [comment]
Okay, thanks for your help !
